### ISSUE TITLE
videojs-preroll example not working

### ISSUE THREAD

**Issue by erik1o6** [dirkjanm/videojs-preroll#10]
videojs-preroll example is not working in chrome. Is there any configuration needed?

**Comment by dirkjanm** [comment]
Do you have it set up online somewhere? Do you see any errors in your error log (browser console)?

**Comment by erik1o6** [comment]
Hi dirkjan,
Yes we are testing it at sivarmunchies.com/oogie

**Comment by Zatara7** [comment]
It's right here: http://www.sivarmunchies.com/oogie/video/ex2/example.html

**Comment by dirkjanm** [comment]
The example requires that you run `npm install` in the directory where you cloned the repository, then it will add a node_modules folder with video.js.
Alternatively you can edit the example.html to point to the video.js javascript file manually. Right now your example is missing the player files.
I will update the documentation soon to better explain this.

**Comment by Zatara7** [comment]
Thank you for the fast reply dirkjanm. I updated the example.html file to include that but still getting one error in the console:
videojs.ads.js:146 Uncaught TypeError: undefined is not a function

**Comment by dirkjanm** [comment]
Try to include a newer version of video.js, the latest is 4.11 while you seem to be using 4.5 here and the current version of the preroll plugin requires at least 4.8 I think.

**Comment by Zatara7** [comment]
Works like a charm now! Thanks

**Comment by dirkjanm** [comment]
No problem :)

**Comment by erik1o6** [comment]
Hi dirkjan,
Yes we are testing it at sivarmunchies.com/oogie
