### ISSUE TITLE
Edit Lang

### ISSUE THREAD

**Issue by tolgatasci** [dirkjanm/videojs-preroll#11]
Hello guy,
skip 5
skip 4
skip 3

LANG 5
LANG 4 
LANG 3
who is replace ?

**Comment by tolgatasci** [comment]
player.vast.skipButton.innerHTML = "Skip in " + timeLeft + "...";

:) ok Thanks good JOOB

**Comment by dirkjanm** [comment]
Yes you should edit these 2 lines:

 player.preroll.skipButton.innerHTML = 'Skip in ' + timeLeft + '...';
 player.preroll.skipButton.innerHTML = 'Skip';
