### ISSUE TITLE
Video.JS 5.0.0 Compability

### ISSUE THREAD

**Issue by philipgiuliani** [dirkjanm/videojs-preroll#12]
Hi! The plugin is currently not compatible with VideoJS 5. I think you just have to do some minor changes. You already have any plans?

**Comment by dirkjanm** [comment]
I haven't had the time to look into VJS 5.0, but once I get around to that I'll see what needs changing to work with the latest VideoJS and videojs-contrib-ads

**Comment by philipgiuliani** [comment]
Thank you! I think they didn't change so much. The first crash is already this line:
https://github.com/dirkjanm/videojs-preroll/blob/master/src/videojs-preroll.js#L24
because the merge function doesn't exist anymore...

**videojs-contrib-ads**
There is a PR open: https://github.com/videojs/videojs-contrib-ads/pull/121

**Upgrade guide for videojs-contrib-ads**
https://github.com/videojs/videojs-contrib-ads/blob/vjs-5-upgrade/migrating-to-3.0.md

**Comment by dirkjanm** [comment]
After a few hours of headaches the fixes are in and available in the vjs5 branch until the videojs-contrib-ads PR is finalized.

**Comment by alijaffar** [comment]
Excellent work, video meister Dirk!

**Comment by misteroneill** [comment]
Quick FYI, but [videojs/videojs-contrib-ads#121](https://github.com/videojs/videojs-contrib-ads/pull/121) has been merged and released as `v3.1.0`.

**Comment by dirkjanm** [comment]
Thanks for the heads up, I was already on it :) 
The 3.1.0 is just a version bump right? I don't see any other changes.

**Comment by misteroneill** [comment]
@dirkjanm There's a really minor addition in videojs/videojs-contrib-ads@774c48a16cbbb77972c9dbd274f503bacc214c5b - that's why it's a minor instead of a patch.
