### ISSUE TITLE
Demo video does not load in plugin example

### ISSUE THREAD

**Issue by suchetha** [dirkjanm/videojs-preroll#15]
I am trying to run videojs-preroll v1.0.0 with videojs-contrib-ads v 3.1.0 and video.js v5.3.0

i have tried my code and the code from the demo, and it still doesn't work. the error i get is as follows
![screenshot_2015-12-08_15-22-31](https://cloud.githubusercontent.com/assets/3387116/11652748/893c40d8-9dbf-11e5-8241-9e846d633e9c.png)

any ideas how i can fix this? my javascript coding is not all that good, so i can't really find where the code goes kaput, but if you need any more information i can provide

all the best

Suchetha

**Comment by dirkjanm** [comment]
What video are you using as ad? This message means the video cannot be loaded, I'm not sure its related to the javascript in this case.

**Comment by suchetha** [comment]
i was using the demo page you had put the code to on 

https://github.com/dirkjanm/videojs-preroll/blob/master/example.html

is there an error there? because i could play the advert you had linked to directly on firefox

**Comment by dirkjanm** [comment]
It seems that the demo video used gives a http 403, so you'll have to update the example to point to a video that actually works, then you shouldn't get this error.
